### ISSUE TITLE
General Game Checklist ( Code)

### ISSUE THREAD

**Issue by saumyamukul** [rmont881/EmojiWarsCC#6]
- [x] Lobby scene -rmont
  - [x] Add as many players as paddles from lobby scene
- [ ] End scene
- [ ] Pause/Settings Menu?
- [ ] Background Music
- [ ] Weapon sounds -jbodily
- [ ] Particle effects for weapon impact -jbodily
- [ ] Weapons
  - [ ] Weapon to immobilize, lift and throw ( Similar to Duck hunt's net)
  - [ ] Grenade
  - [ ] Simple gun
- [ ] Player states ( Alive/Dead) or health
- [ ] Clean up multi-controller support -rmont
